# Generated by Django 3.2.4 on 2021-06-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
