# Generated by Django 3.2.4 on 2021-06-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_news_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_datetime',
        ),
        migrations.AddField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
