# Generated by Django 3.2.4 on 2021-07-02 10:31

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_alter_news_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
