# Generated by Django 3.1.6 on 2021-06-12 00:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sandans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandan',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sandan',
            name='age',
        ),
        migrations.RemoveField(
            model_name='sandan',
            name='array',
        ),
        migrations.RemoveField(
            model_name='sandan',
            name='belong',
        ),
        migrations.RemoveField(
            model_name='sandan',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='sandan',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='sandan',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='sandan',
            name='sex',
        ),
        migrations.AddField(
            model_name='sandan',
            name='books',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='sandan',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sandan',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='sandan',
            name='waittime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sandan',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
