# Generated by Django 3.2.4 on 2021-06-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default='No Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
